package ui;

import java.util.Random;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import logica.Jugador;

/**
 *
 * @author Francisco Javier Araujo Mendoza
 */
public class MenuPrincipal extends javax.swing.JFrame {

    PanelAhorcado pAhorcado;
    Jugador j1, j2;
    VentanaPartida vp;
    Boolean turno;      //Turno para elegir palabra, true = j1, false = j2

    /**
     * Creates new form MenuPrincipal
     */
    public MenuPrincipal() {
        initComponents();
        pAhorcado = new PanelAhorcado(7, panelLogo);
        panelLogo.add(pAhorcado);
        j1 = null;
        j2 = null;
        turno = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelTitulo = new javax.swing.JLabel();
        panelLogo = new javax.swing.JPanel();
        botonInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Ahorcado");
        setResizable(false);

        labelTitulo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        labelTitulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTitulo.setText("Ahorcado");

        panelLogo.setLayout(null);

        botonInicio.setText("Nueva partida");
        botonInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonInicioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                    .addComponent(botonInicio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(botonInicio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void botonInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonInicioActionPerformed
        String nombre = null;
        
        if (j1 == null) {
            while (nombre == null || "".equals(nombre)) {
                nombre = JOptionPane.showInputDialog(this, "Introduce tu nombre", "Crear Jugador 1", JOptionPane.QUESTION_MESSAGE);
                if (nombre == null || "".equals(nombre)) {
                    JOptionPane.showMessageDialog(this, "Debes introducir tu nombre", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            j1 = new Jugador(nombre);
        }
        nombre = null;
        if (j2 == null) {
            while (nombre == null || "".equals(nombre)) {
                nombre = JOptionPane.showInputDialog(this, "Introduce tu nombre", "Crear Jugador 2", JOptionPane.QUESTION_MESSAGE);
                if (nombre == null || "".equals(nombre)) {
                    JOptionPane.showMessageDialog(this, "Debes introducir tu nombre", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
            j2 = new Jugador(nombre);
        }
        if (turno == null) {
            turno = new Random().nextBoolean();
        } else {
            turno = !turno;
        }

        JOptionPane.showMessageDialog(this, "Es el turno de " + (turno ? j1.getNombre() : j2.getNombre()) + " para escribir,\npulsa OK para introducir la palabra", "Nueva partida", JOptionPane.INFORMATION_MESSAGE);
        String palabra = null;
        boolean valida = false;
        while (!valida) {  
            JPasswordField palabraField = new JPasswordField();
            JOptionPane.showMessageDialog(this, palabraField, "Introduce la palabra", JOptionPane.QUESTION_MESSAGE);
            palabra = String.valueOf(palabraField.getPassword());

            if (palabra == null || "".equals(palabra)) {
                JOptionPane.showMessageDialog(this, "Debes introducir alguna palabra", "Error", JOptionPane.ERROR_MESSAGE);
            } else {
                if (palabra.matches("^[a-zA-Z\u00C0-\u024F\u1E00-\u1EFF]*$")) //alfanumérico sin espacios, con caracteres latinos extra, como acentos y ñ
                {
                    valida = true;
                } else {
                    JOptionPane.showMessageDialog(this, "No puede contener ni espacios ni números", "Error", JOptionPane.ERROR_MESSAGE);
                }
            }
        }

        //iniciar partida
        vp = new VentanaPartida(palabra, this, turno ? j2.getNombre() : j1.getNombre());
        this.setVisible(false);
        vp.setVisible(true);


    }//GEN-LAST:event_botonInicioActionPerformed

    public void partidaFin(boolean gano) {
        Jugador ganador;
        if (gano) {
            ganador = turno ? j2 : j1;
        } else {
            ganador = turno ? j1 : j2;
        }
        
        ganador.haGanado();
        JOptionPane.showMessageDialog(vp,
                "Enhorabuena " + ganador.getNombre() + ", has ganado esta ronda\n"
                + "Llevas " + ganador.getGanadas() + " partidas ganadas",
                "Fin de la partida",
                JOptionPane.INFORMATION_MESSAGE
        );
        vp.dispose();
        this.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            javax.swing.UIManager.setLookAndFeel(javax.swing.UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                MenuPrincipal mp = new MenuPrincipal();
                mp.setLocationRelativeTo(null);
                mp.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonInicio;
    private javax.swing.JLabel labelTitulo;
    private javax.swing.JPanel panelLogo;
    // End of variables declaration//GEN-END:variables
}
